---
title: "MSM Modeling"
format: html
editor: visual
---

## Data

```{r}
library(msm)
library(tidyverse)
#use fread or read.csv
nba <- read.csv("nba_1S_100P_long.csv")
nba <- nba %>%
  filter(game_time_min <= 48)

```

```{r}
nba
```

## Continuous-State Hidden Markov Model

## One Player/All games

```{r}
library(msm)

#filter
g <- nba %>%
  filter(player == "shai_gilgeous_alexander") %>%
  arrange(game_id, game_time_min, row_id)


#resdiulize using lm
# g <- g %>%
#   group_by(game_id) %>%
#   mutate(
#     Perf_resid = resid(lm(Perf ~ game_time_min))
#   ) %>%
#   ungroup()

```

```{r}
# Build initial emission params for 3 states 
cuts <- quantile(g$Perf, probs = c(1/3, 2/3), na.rm = TRUE)

# 3 states 
g <- g %>%
  mutate(init_state = case_when(
    Perf <= cuts[1] ~ 1L,      # cold
    Perf <= cuts[2] ~ 2L,      # normal
    TRUE ~ 3L                 # hot
  ))

init_means <- tapply(g$Perf, g$init_state, mean, na.rm = TRUE)
init_sds   <- tapply(g$Perf, g$init_state, sd, na.rm = TRUE)

# guard against sd=0 or NA
init_sds[!is.finite(init_sds) | init_sds <= 1e-6] <- sd(g$Perf, na.rm = TRUE)
init_sds[!is.finite(init_sds) | init_sds <= 1e-6] <- 1

#hmodel
hmodel <- list(
  hmmNorm(mean = init_means[1], sd = init_sds[1]),
  hmmNorm(mean = init_means[2], sd = init_sds[2]),
  hmmNorm(mean = init_means[3], sd = init_sds[3])
)

# transition matrix (check rate matrix)
Q <- rbind(
  c(0,   0.15, 0),   # 1 -> 2
  c(0.15, 0,   0.15),# 2 -> 1 or 3
  c(0,   0.15, 0)    # 3 -> 2
)
```

```{r}
# Fit hmm
m <- msm(
  Perf ~ game_time_min,
  subject = game_id,
  data = g,
  qmatrix = Q,
  hmodel = hmodel,
  center = FALSE,
  control = list(maxit = 1000)
)

summary(m)


# Decode most likely hidden state sequence 
g$state_hat <- viterbi.msm(m)

# state meams
m$hmodel

```

```{r}

```

```{r}
```

## Preliminary Full Model

```{r}

```

```{r}

```
